server:
  port: 8086

spring:
  application:
    name: api-gateway
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    configUrl: /v3/api-docs/swagger-config
    url: /v3/api-docs

services:
  file-storage:
    url: http://localhost:8080
  file-analysis:
    url: http://localhost:8082

---
spring:
  config:
    activate:
      on-profile: docker

services:
  file-storage:
    url: http://file-storing-service:8080
  file-analysis:
    url: http://file-analysis-service:8082 