server:
  port: 8082

spring:
  application:
    name: file-analysis-service
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://db:5432/plagiat
    username: plagiat
    password: plagiat
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    configUrl: /v3/api-docs/swagger-config
    url: /v3/api-docs

file:
  storage:
    url: http://file-storing-service:8080 